### PR TITLE
Add partial import

### PR DESCRIPTION
**Pull request by rusminto**
UPDATE:  
- add test feature
- add options compareExisting on importFile, like this  
```js
await importer.init(config.db)
.read(filepath)
.importFile({
    dropFirst: false,
    compareExisting: true
});
```  

already tested :  
image

### CODE REVIEW

**Comment by iqrok** [comment]
Test failed on partial import

```powershell
PS E:\sd\nodejs\npm-publish\sql-importer> npm test

> sql-file-importer@0.0.3-alpha.1 test
> cd test && npm run test


> test@0.0.1 test
> jest --forceExit --detectOpenHandles --runInBand

 FAIL  module/all.test.js
  From PMA's export
    √ Delete all tables and routine (122 ms)
    √ Import db structure and data (71 ms)
    √ Delete all tables and routine (27 ms)
    √ Import db structure only (77 ms)
    √ Delete all tables and routine (25 ms)
    √ Import db without dropping all tables and routines first (50 ms)
    × Import partially (Add Empty Column) (140 ms)
    × Import partially (Add Empty Table) (174 ms)

  ● From PMA's export › Import partially (Add Empty Column)

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      144 |         // check if table has column "itemCode"
      145 |         const isTableHasItemCode = await gen.checkTableHasItemCode()
    > 146 |         expect(isTableHasItemCode).toBe(true)
          |                                    ^
      147 |
      148 |         // check if table has column "itemCode" and has content
      149 |         const isTableHasItemCodeContent = await gen.checkTableHasItemCodeContent()

      at Object.toBe (module/all.test.js:146:36)

  ● From PMA's export › Import partially (Add Empty Table)

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      188 |         // check if table has column "itemCode"
      189 |         const isTableHasItemCode = await gen.checkTableHasItemCode()
    > 190 |         expect(isTableHasItemCode).toBe(true)
          |                                    ^
      191 |
      192 |         // check if table has column "itemCode" and has content
      193 |         const isTableHasItemCodeContent = await gen.checkTableHasItemCodeContent()

      at Object.toBe (module/all.test.js:190:36)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 6 passed, 8 total
Snapshots:   0 total
Time:        1.211 s, estimated 2 s
Ran all test suites.
```

node v18.12.1
mariadb 10.4.6

**Comment by rusminto** [comment]
hmm i've already try it again, and it still works:  
```bash
 rusminto@rusminto : ~/sql-importer>  npm test

> sql-file-importer@0.0.3-alpha.1 test
> cd test && npm run test


> test@0.0.1 test
> jest --forceExit --detectOpenHandles --runInBand

 PASS  module/all.test.js
  From PMA's export
    ✓ Delete all tables and routine (70 ms)
    ✓ Import db structure and data (43 ms)
    ✓ Delete all tables and routine (15 ms)
    ✓ Import db structure only (31 ms)
    ✓ Delete all tables and routine (15 ms)
    ✓ Import db without dropping all tables and routines first (29 ms)
    ✓ Import partially (Add Empty Column) (16 ms)
    ✓ Import partially (Add Empty Table) (25 ms)

Test Suites: 1 passed, 1 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        0.459 s, estimated 1 s
Ran all test suites.
```  

node v18.13.0
mariadb  Ver 15.1

**Comment by rusminto** [comment]
After run all tests, can you run query :
```sql
SELECT COUNT(1) as total
        FROM information_schema.COLUMNS 
        WHERE 
            TABLE_SCHEMA = "your_db"
        AND TABLE_NAME = 'd_access_proposal' 
        AND COLUMN_NAME = 'itemCode'
```
from [this](https://github.com/iqrok/sql-importer/blob/9a22b347daf87985e7ef02ac1c94dc934f139cbf/test/module/general.js#L60) on your database.  

Or check manually if column 'itemCode' exist in your 'd_access_proposal'.  

Or check if you already pull latest commit, and check whether "https://github.com/iqrok/sql-importer/blob/9a22b347daf87985e7ef02ac1c94dc934f139cbf/sample/from_pma_add_column.sql" exist in your sample directory

**Comment by iqrok** [comment]
Running it again on different machine, the test ran successfully

```bash
$ npm test 

> sql-file-importer@0.0.3-alpha.1 test
> cd test && npm run test


> test@0.0.1 test
> jest --forceExit --detectOpenHandles --runInBand

 PASS  module/all.test.js
  From PMA's export
    ✓ Delete all tables and routine (111 ms)
    ✓ Import db structure and data (109 ms)
    ✓ Delete all tables and routine (31 ms)
    ✓ Import db structure only (104 ms)
    ✓ Delete all tables and routine (32 ms)
    ✓ Import db without dropping all tables and routines first (101 ms)
    ✓ Import partially (Add Empty Column) (27 ms)
    ✓ Import partially (Add Empty Table) (107 ms)

Test Suites: 1 passed, 1 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        0.902 s, estimated 2 s
Ran all test suites.
```

**Comment by rusminto** [comment]
hmm okay

**Pull request merged**
